apiVersion: v1
kind: Secret
metadata:
  name: driving-secret
type: Opaque
stringData:
  EMAIL_HOST_USER: "newandajmotordrivingschool@gmail.com"
  EMAIL_HOST_PASSWORD: "dyap fmqd ngxk hrhn"

  DATABASE_PASSWORD: "2874"

  SECRET_KEY: "arvind09112004"

  DATABASE_URL: "postgresql://neondb_owner:npg_PLA1vZYSpu9Q@ep-withered-term-a59ozhc5-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
